version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    env_file:
      - backend/.env
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
